version: '2'
services:
    metric:
        image: kgoyo/flixmetric

        ports:
          - "8081:8081"

        restart: always

        # Dependant on the 'mongo' container running, since it's our storage
        depends_on:
            - mongo
    mongo:
        image: mongo:3.6.3

        volumes:
          - ./data:/data/db

        command: --smallfiles --noprealloc