version: '3.4'

x-user: &user-template
  # basic user setup, used for extending
  image: andreasmalling/ft_user
  build: ./user
  volumes:
    - ./video_dashed/:/usr/src/app/video_dashed/
  depends_on:
    - bootstrap
    - metric
    - network
    - host

services:    
    user_seed:
      # user which adds content from videos_dashed to local IPFS network
      <<: *user-template
      command: ["--seed" ,"IDLE"]

    user_manual:
      # user for debugging
      <<: *user-template
      privileged: true  #Sound
      environment:
        - DISPLAY=$DISPLAY  #Display
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix  #Display
        - /dev/snd:/dev/snd  #Sound
      command: ["-m", "IDLE"]
        

    bootstrap:
      # IPFS node used for bootstraping local network
      image: andreasmalling/ft_bootstrap

    host:
      # python server hosting the website for the web player
      # the web player can be found on "host/webplayer.html"
      image: andreasmalling/ft_host
      build: ./website
      volumes:
        - ./website:/usr/src/app/

    metric:
      # mongoDB client to whom users report
      image: kgoyo/flixmetric
      build: ./metric_server
      restart: always
      # Dependant on the 'mongo' container running, since it's our storage
      depends_on:
          - mongo
    
    network:
      # collects network data from user containers
      image: andreasmalling/ft_network
      build: ./network_logger
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
          - mongo
    
    mongo:
      # mongoDB microservice
      image: mongo:3.6.3
      volumes:
        - ./data:/data/db
      command: --smallfiles --noprealloc