version: '3.5'
services:
    bootstrap:
        image: andreasmalling/ft_bootstrap
    user_contentadder:
        image: andreasmalling/ft_user

        volumes:
          - ./video_dashed/:/usr/src/app/video_dashed/

        command: ["--host" ,"IDLE"]

        depends_on:
          - bootstrap

    user_manual:
        # manual user with debug purpose 
        image: andreasmalling/ft_user

        privileged: true

        environment:
            - DISPLAY=$DISPLAY #Display
        
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix #Display
          - /dev/snd:/dev/snd #Sound
          - ./video_dashed/:/usr/src/app/video_dashed/

        command: ["-m", "IDLE"]

        depends_on:
          - metric
          - network
          - host
          - bootstrap
    
    host:
        #python server hosting the website for the web player
        # the web player can be found on "host:8000/webplayer.html"
        image: andreasmalling/ft_host

        volumes:
          - ./website:/usr/src/app/

    metric:
        image: kgoyo/flixmetric

        restart: always

        # Dependant on the 'mongo' container running, since it's our storage
        depends_on:
            - mongo
    network:
        image: andreasmalling/ft_network
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    mongo:
        image: mongo:3.6.3

        volumes:
          - ./data:/data/db

        command: --smallfiles --noprealloc