version: '3.5'
services:
    bootstrap:
        image: andreasmalling/ft_bootstrap
    client:
        image: andreasmalling/ft_user

        #these 2 are only necessary for when we want to see the containers browser
        environment:
            - DISPLAY=$DISPLAY
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ./video_dashed/:/usr/src/app/video_dashed/

        # commands for the flixtube client
        command: ["-m"]

        depends_on:
          - metric
          - network_logger
          - host
          - bootstrap
    host:
        #python server hosting the website for the web player
        # the web player can be found on "host:8000/webplayer.html"
        image: kgoyo/flixtube_host

    metric:
        image: kgoyo/flixmetric

        restart: always

        # Dependant on the 'mongo' container running, since it's our storage
        depends_on:
            - mongo
    network_logger:
        image: kgoyo/flixmetric
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    mongo:
        image: mongo:3.6.3

        volumes:
          - ./data:/data/db

        command: --smallfiles --noprealloc