version: '3.5'
services:
    bootstrap:
        image: andreasmalling/flixtube_bootstrap
    client:
        image: andreasmalling/flixtube

        #these 2 are only necessary for when we want to see the containers browser
        environment:
            - DISPLAY=$DISPLAY
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix

        # commands for the flixtube client
        command: ["-m"]

        depends_on:
          - metric
          - host
    host:
        #python server hosting the website for the web player
        # the web player can be found on "host:8000/webplayer.html"
        image: kgoyo/flixtube_host

    metric:
        image: kgoyo/flixmetric

        restart: always

        # Dependant on the 'mongo' container running, since it's our storage
        depends_on:
            - mongo
    mongo:
        image: mongo:3.6.3

        volumes:
          - ./data:/data/db

        command: --smallfiles --noprealloc