version: '3.5'

# basic user setup, used for extending
# source: https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-user: &user-template
  image: andreasmalling/ft_user
  build: ./user
  volumes:
    - ./video_dashed/:/usr/src/app/video_dashed/
  command: "IDLE"
  depends_on:
    - bootstrap
    - metric
    - network
    - host

services:
#  _____  ______ _____   _____  ____  _   _           _____ 
# |  __ \|  ____|  __ \ / ____|/ __ \| \ | |   /\    / ____|
# | |__) | |__  | |__) | (___ | |  | |  \| |  /  \  | (___  
# |  ___/|  __| |  _  / \___ \| |  | | . ` | / /\ \  \___ \ 
# | |    | |____| | \ \ ____) | |__| | |\  |/ ____ \ ____) |
# |_|    |______|_|  \_\_____/ \____/|_| \_/_/    \_\_____/ 
#                                                          
  
  # user for debugging, with sound and display pass-through
  user_debug:
    <<: *user-template
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/snd:/dev/snd
    command: ${USER_DEBUG:- --head IDLE}

  # user which adds content from videos_dashed to local IPFS network
  user_seed:
    <<: *user-template
    command: ${USER_SEED:- --seed IDLE}
  
  user_1:
    <<: *user-template
    command: ${USER_1}

  user_2:
    <<: *user-template
    command: ${USER_2}

  user_3:
    <<: *user-template
    command: ${USER_3}

  user_4:
    <<: *user-template
    command: ${USER_4}

  user_5:
    <<: *user-template
    command: ${USER_5}

  user_6:
    <<: *user-template
    command: ${USER_6}

#  _______ _    _ ______      _____  ______  _____ _______ 
# |__   __| |  | |  ____|    |  __ \|  ____|/ ____|__   __|
#    | |  | |__| | |__       | |__) | |__  | (___    | |   
#    | |  |  __  |  __|      |  _  /|  __|  \___ \   | |   
#    | |  | |  | | |____     | | \ \| |____ ____) |  | |   
#    |_|  |_|  |_|______|    |_|  \_\______|_____/   |_|   
#                                                          

  # IPFS node used for bootstraping local network
  bootstrap:
    image: andreasmalling/ft_bootstrap

  # python server hosting the website for the web player
  # the web player can be found on "host/webplayer.html"
  host:
    image: andreasmalling/ft_host
    build: ./website
    volumes:
      - ./website:/usr/src/app/

  # mongoDB client to whom users report
  metric:
    image: andreasmalling/ft_metric
    build: ./metric_server
    restart: always
    # Dependant on the 'mongo' container running, since it's our storage
    depends_on:
        - mongo
  
  # collects network data from user containers
  network:
    image: andreasmalling/ft_network
    build: ./network_logger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - mongo
  
  # mongoDB microservice
  mongo:
    image: mongo:3.6.3
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/data/dump
    command: --smallfiles --noprealloc
  